name:                machine
version:             0.0.0.1
github:              hilcode/machine
homepage:            https://github.com/hilcode/machine#readme
copyright:           2020 Hilco Wijbenga
license:             GPL-3
author:              Hilco Wijbenga
maintainer:          Hilco Wijbenga
category:            Utility

extra-source-files:
- README.md

default-extensions:
- BangPatterns
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoMonomorphismRestriction
- OverloadedStrings
- ScopedTypeVariables
- Strict
- TupleSections
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wtabs
- -Wno-name-shadowing

dependencies:
- base >= 4.7 && < 5
- containers
- hedgehog
- hspec
- hw-hspec-hedgehog
- text
- text-builder
- vector

executables:
  machine:
    source-dirs:
      - src/main/haskell
    main: Main.hs
    dependencies:
      - machine

library:
  source-dirs:
    - src/main/haskell
  exposed-modules:
    - Hilcode.Misc.Internal

tests:
  test:
    source-dirs:
      - src/test/haskell
    main: Spec.hs
    dependencies:
      - base
      - machine
    other-modules:
      - Hilcode.MiscSpec
